name: elcoma
description: 'An application for managing electronic components easily.'
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.20
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  polymer: ^1.0.0-rc.2
  polymer_elements: ^1.0.0-rc.9
  web_components: ^0.12.0
transformers:
- polymer:
    entry_points:
    - web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
